# syntax=docker/dockerfile:1
ARG VARIANT="3.11-bullseye"
FROM mcr.microsoft.com/devcontainers/python:${VARIANT}

# Install system dependencies if needed in the future
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <package-list> \
#     && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
